name: Checks

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  pod-lint:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.3"
      - uses: actions/checkout@v2
      - name: Run lint
        run: pod lib lint --allow-warnings

  build-xcodebuild:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.3"
      - uses: actions/checkout@v2
      - name: xcodebuild
        run: xcodebuild -scheme BulkLogger -sdk iphoneos -destination 'generic/platform=iOS'

  build-swiftpm:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.3"
      - uses: actions/checkout@v2
      - name: SwiftPM
        run: swift build

  test:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.3"
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run
        run: |
          swift test
