name: Checks

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build-xcodebuild:
    runs-on: macos-15

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "16.4"
      - uses: actions/checkout@v2
      - name: xcodebuild
        run: set -o pipefail && xcodebuild -scheme Bulk-Package -sdk iphoneos -destination 'generic/platform=iOS' | xcbeautify

  test:
    runs-on: macos-15

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "16.4"
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run
        run: |
          set -o pipefail && xcodebuild -scheme Bulk-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16 Pro' test | xcbeautify
