name: Checks

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build-xcodebuild:
    runs-on: macos-14

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "16.0"
      - uses: actions/checkout@v2
      - name: xcodebuild
        run: xcodebuild -scheme BulkLogger -sdk iphoneos -destination 'generic/platform=iOS'

  test:
    runs-on: macos-14

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "16.0"
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run
        run: |
          swift test
